apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: <kibana-name>
spec:
  version: 8.7.0
  count: 1
  elasticsearchRef:
    name: "<kind-elasticsearch-metadata-name>"
  # See below for fleet configuration:
  #config:
  #  xpack.fleet.agents.elasticsearch.hosts: ["https://<elasticsearch-metadata-name>-es-http.default.svc:9200"]
  #  xpack.fleet.agents.fleet_server.hosts: ["https://<fleet-server-metadata-name>-agent-http.default.svc:8220"]
  #  xpack.fleet.packages:
  #    - name: system
  #      version: latest
  #    - name: elastic_agent
  #      version: latest
  #    - name: fleet_server
  #      version: latest
  #  xpack.fleet.agentPolicies:
  #    - name: Fleet Server on ECK policy
  #      id: eck-fleet-server
  #      is_default_fleet_server: true
  #      namespace: default
  #      monitoring_enabled:
  #        - logs
  #        - metrics
  #      unenroll_timeout: 900
  #      package_policies:
  #      - name: fleet_server-1
  #        id: fleet_server-1
  #        package:
  #          name: fleet_server
  #    - name: Elastic Agent on ECK policy
  #      id: eck-agent
  #      namespace: default
  #      monitoring_enabled:
  #        - logs
  #        - metrics
  #      unenroll_timeout: 900
  #      is_default: true
  #      package_policies:
  #        - name: system-1
  #          id: system-1
  #          package:
  #            name: system
  http:
    service:
      spec:
        type: LoadBalancer
  # this shows how to customize the Kibana pod
  # with labels and resource limits
  podTemplate:
    metadata:
      labels:
      #  foo: bar
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 2Gi
            cpu: 1
